### ISSUE TITLE
validator makes skill useless

### ISSUE THREAD

**Issue by Tutorialwork** [craigh411/alexa-request-validator#2]
When I use your validator:

`<?php
$JSONRequest = file_get_contents("php://input");
$request = json_decode($JSONRequest, TRUE);
if(empty($request) || (!isset($request))){
    http_response_code(400);
    exit;
}

$validator = new \Humps\AlexaRequest\AlexaRequestValidator('amzn1.ask.skill.4afad9d0-2a65-4c7f-b193-ca67c6085907', file_get_contents('php://input'), $_SERVER['HTTP_SIGNATURECERTCHAINURL'], $_SERVER['HTTP_SIGNATURE']);
try {
    if($validator->validateRequest()){
      // Accept request to your service
//my code......
    }
    // Reject request with a 500 error, hopefully this shouldn't happen!
  }catch(\Humps\AlexaRequest\Exceptions\AlexaValidationException $e) { 
    // Reject the request with a 400 error or the given error code (via $e->getCode()) with the returned message ($e->getMessage())
  }
?>`

I get this error message: There was a problem answering the requested skill

Here is the json input:

`{
	"version": "1.0",
	"session": {
		"new": false,
		"sessionId": "amzn1.echo-api.session.7ddd20d3-0170-4149-aea6-2ea62c5ea88e",
		"application": {
			"applicationId": "amzn1.ask.skill.4afad9d0-2a65-4c7f-b193-ca67c6085907"
		},
		"user": {
			"userId": "amzn1.ask.account.AEBQBAJVNJCA6G5PRHMNOAUAJ2I243SSC7MZ56JTXDLBSDADDXSOI6U3AS3MWSA26MBDK2S4A22JDQJMEPMMFZDJPAVOCF4UZRJ47H6ENI2ZORNOMRR6OKPBK5M5DLBQ4HJB4FL3LP7GHWPIDB3T6KQKL5GRNNNXJFV7ILGYSA4VIY6P4GES2HMH4OKHPRZTX3L4AAUFFP6HCRA"
		}
	},
	"context": {
		"System": {
			"application": {
				"applicationId": "amzn1.ask.skill.4afad9d0-2a65-4c7f-b193-ca67c6085907"
			},
			"user": {
				"userId": "amzn1.ask.account.AEBQBAJVNJCA6G5PRHMNOAUAJ2I243SSC7MZ56JTXDLBSDADDXSOI6U3AS3MWSA26MBDK2S4A22JDQJMEPMMFZDJPAVOCF4UZRJ47H6ENI2ZORNOMRR6OKPBK5M5DLBQ4HJB4FL3LP7GHWPIDB3T6KQKL5GRNNNXJFV7ILGYSA4VIY6P4GES2HMH4OKHPRZTX3L4AAUFFP6HCRA"
			},
			"device": {
				"deviceId": "amzn1.ask.device.AHJA7AAXGO2UQIZHUJNNAXJX2CG425XO47TIYKKDMRAP5GPQ4TM4RARP6KMTYXAUCK75LVA7NEVM5U2JHDA35N4U7BPVURO7ZC7RBM2NOWOUICKDEJGW6PUXKDFLAC3IS2CE3C7Q6JXACMOG55ZBS3YZVMZA",
				"supportedInterfaces": {}
			},
			"apiEndpoint": "https://api.eu.amazonalexa.com",
			"apiAccessToken": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IjEifQ.eyJhdWQiOiJodHRwczovL2FwaS5hbWF6b25hbGV4YS5jb20iLCJpc3MiOiJBbGV4YVNraWxsS2l0Iiwic3ViIjoiYW16bjEuYXNrLnNraWxsLjRhZmFkOWQwLTJhNjUtNGM3Zi1iMTkzLWNhNjdjNjA4NTkwNyIsImV4cCI6MTU2NDgzNjgzMSwiaWF0IjoxNTY0ODM2NTMxLCJuYmYiOjE1NjQ4MzY1MzEsInByaXZhdGVDbGFpbXMiOnsiY29udGV4dCI6IkFBQUFBQUFBQVFDZnJXc1VNdlRFbStrU1M2QTBsMTc4SkFFQUFBQUFBQUFNNEhmYm5uS1BNbENENW5MeXE4SG1CbkVCSHZSdkF4WkNXTGhGSjV0Qk5zNVMzU0s2eFl2TkhQcnZZckw5M2JmMDd6L284MXVJYlZCdVVqS1NOTVlGYU1ud2xWeHhDL3ZBdWEwVnNnTW05Zi94VmpnTVY2T3ZHVkJjNC9kUnNIa2ZibUJiYTJBRFAxdmlOU2N1S2sySFY0QkRiZ29wN2wyaHo5Z3lYSHNGeU5qVW8xZEdNRG9ubzdjWWZVb2hCamZvcEFaVkNvd1ArT2tLQXVjZFZpYjZmVy9PNGxiMjloNjh1UVhDZzdXemM0Q1FKRlZvWFl6a0NlWjBPK2xJTzV1Z3VSNDdVRDU0eGR0WUltWndMdDFPMnlSWENFbXpndXZJVUVNNUg1Y0xjeXFiUmxMcXMwQlgvem1XY1VqNE1MVnRic3FFTHRBZFdNNldhVXBKRmdQUkZhNEdadE5aa3htakFoZmFuWStlZElCUnFEMEZZMWZETWl4U1ZkTHRCOFdVT24wZCIsImNvbnNlbnRUb2tlbiI6bnVsbCwiZGV2aWNlSWQiOiJhbXpuMS5hc2suZGV2aWNlLkFISkE3QUFYR08yVVFJWkhVSk5OQVhKWDJDRzQyNVhPNDdUSVlLS0RNUkFQNUdQUTRUTTRSQVJQNktNVFlYQVVDSzc1TFZBN05FVk01VTJKSERBMzVONFU3QlBWVVJPN1pDN1JCTTJOT1dPVUlDS0RFSkdXNlBVWEtERkxBQzNJUzJDRTNDN1E2SlhBQ01PRzU1WkJTM1laVk1aQSIsInVzZXJJZCI6ImFtem4xLmFzay5hY2NvdW50LkFFQlFCQUpWTkpDQTZHNVBSSE1OT0FVQUoySTI0M1NTQzdNWjU2SlRYRExCU0RBRERYU09JNlUzQVMzTVdTQTI2TUJESzJTNEEyMkpEUUpNRVBNTUZaREpQQVZPQ0Y0VVpSSjQ3SDZFTkkyWk9STk9NUlI2T0tQQks1TTVETEJRNEhKQjRGTDNMUDdHSFdQSURCM1Q2S1FLTDVHUk5OTlhKRlY3SUxHWVNBNFZJWTZQNEdFUzJITUg0T0tIUFJaVFgzTDRBQVVGRlA2SENSQSJ9fQ.k3PlHq0v0sjdzihu7Qg0Yudfobqhxw4wIhoJgA2pWQt1tXFd05guXD9T9S6Gg1ZXoRElPa2X87jy9gU4mePP9efZ9SrRqW4ZYvRo7cixXBbBcUHb7YshWRjxH6giFMK3n7aBhQ3_wVCdvWvaOWZsQYRv-tw-rd7ML0Mg5-XkG4eN06EKtg7wr38IGgH1-yFFXDmtnw8h37K5WsKCmBt0CtcIT_-ldl76mX4a_h_AOAis5kGHWpNMEMk-rTaD2OPT8csVnCrpVx07e6D8VRDA4sqPh6sNioQwyNdI-Adc3JRlL9MpVyHdZ4hDxA5zXuD7u73AT8U42oiHZHNxckOixg"
		},
		"Viewport": {
			"experiences": [
				{
					"arcMinuteWidth": 246,
					"arcMinuteHeight": 144,
					"canRotate": false,
					"canResize": false
				}
			],
			"shape": "RECTANGLE",
			"pixelWidth": 1024,
			"pixelHeight": 600,
			"dpi": 160,
			"currentPixelWidth": 1024,
			"currentPixelHeight": 600,
			"touch": [
				"SINGLE"
			],
			"video": {
				"codecs": [
					"H_264_42",
					"H_264_41"
				]
			}
		}
	},
	"request": {
		"type": "SessionEndedRequest",
		"requestId": "amzn1.echo-api.request.f5addb67-5b81-42ec-83f5-54dcd2048aa3",
		"timestamp": "2019-08-03T12:48:52Z",
		"locale": "de-DE",
		"reason": "ERROR",
		"error": {
			"type": "INVALID_RESPONSE",
			"message": "An exception occurred while dispatching the request to the skill."
		}
	}
}`

**Comment by craigh411** [comment]
Does this happen without the validator? I use this in my skills - which have handled millions of requests - without issue. I would suggest doing a Google search for the error message "An exception occurred while dispatching the request to the skill." to see if there is anything else that could be the problem.

**Comment by Tutorialwork** [comment]
Thank you. The issue was from my code.
